name: umc dev CI/CD

on:
  pull_request:
    types: [closed] # Pull Request가 닫힐 때만 실행
  workflow_dispatch: # 수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # OS 환경
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev' # merge가 되었고 && 대상이 dev 브랜치면 실행

    steps:
      - name: Checkout # github가 알아서 checkout 함
        uses: actions/checkout@v2 # github에서 제공하는 actions 중 checkout의 @ v2 버전 사용. 해당 .github가 위치한 이후에 있는 폴더만 빌드함.

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      # ubuntu에서 돌아가는 거 -> 파일 생성하든 뭔가를 하려면 권한 필요 -> 그거 해주는 작업
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # gradlew에 실행 권한 부여
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test # test는 실행하지 않음
        shell: bash

      - name: Get current time
        uses: 1466587594/get=current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: '+09:00'

      - name: Show Current Time
        run: echo "CuurentTime=$"
        shell: bash

        # deploy 폴더에 jar 파일 복사
        # Procfile 복사 (리눅스에서 make file 비슷한거?)
        # .ebextensions(elastic beanstalk)에 뭔가 해달라고 요청하는
        # 추가적인 플랫폼과 관련된 명령어(nginx, was 등)를 넣어주는
        # 마지막은 압축하는 것
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar 
          cp Procfile deploy/Procfile
          cp -r .ebextensions_dev deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

        - name: Beanstalk Deploy
            uses: einaregilsson/beanstalk-deploy@v20
            with:
              aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
              aws_secret_key: ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
              application_name: umc-dev
              environment_name: Umc-dev-env
              version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
              region: ap-northeast-2
              deployment_package: deploy/deploy.zip
              wait_for_deployment: false